print("            Caluclator               ")          
print()
print("Hello, I am your your calcualtor.")
print("I can add, subtract, multiply, and divide.")
print("If you want to add, type 'Add'.")
print("If you want to subtract, type 'Subtract'.")
print("If you want to multiply, type 'Multiply'.")
print("If you want to divide, type 'Divide'." )
operation = input("What do you want to do?")
if operation == "Add":
  print("You have chosen to add.")
  x = input("Type the first number: ")
  y = input("Type the second number: ")
  sum = int(x) + int(y) 
  print("The sum is: ", sum)
elif operation == "Subtract":
  print("You have chosen to subtract")
  x = input("Type the first number: ")
  y = input("Type the second number: ")
  difference = int(x) - int(y) 
  print("The difference is: ", difference)
elif operation == "Multiply":
  print("You have chosen to multiply")
  x = input("Type the first number: ")
  y = input("Type the second number: ")
  product = int(x) * int(y) 
  print("The product is: ", product)
elif operation == "Divide":
  print("You have chosen to divide")
  x = input("Type the first number: ")
  y = input("Type the second number: ")
  quotient = int(x) / int(y) 
  print("The quotient is: ", quotient)
